[package]
name = "mercury_mir_build"
description = "Lowers the type-checked Mercury AST into MIR."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
mercury_span = { workspace = true }
mercury_diag = { workspace = true }
mercury_ast = { workspace = true }
mercury_types = { workspace = true }
mercury_mir = { workspace = true }
mercury_sema = { workspace = true }

[dev-dependencies]
mercury_parser = { workspace = true }
