[package]
name = "wukong_opt"
description = "The Wukong optimizer: a pass manager and MIR transforms."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
wukong_mir = { workspace = true }
wukong_span = { workspace = true }

[dev-dependencies]
wukong_parser = { workspace = true }
wukong_sema = { workspace = true }
wukong_mir_build = { workspace = true }
wukong_interp = { workspace = true }
