[package]
name = "wukong_sema"
description = "Semantic analysis for Wukong: name resolution, type checking, shape checking."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
wukong_span = { workspace = true }
wukong_diag = { workspace = true }
wukong_ast = { workspace = true }
wukong_types = { workspace = true }

[dev-dependencies]
wukong_parser = { workspace = true }
