//! `examples/gpt2_config.wk` is the single source of truth for the offsets every GPT-2 example
//! uses to index the flat f32 weight blob, and it is GENERATED by `tools/export_gpt2.py`. Nothing
//! tied the two together: `grep -rl 'GPT2_TOTAL_WEIGHTS\|GPT2_LAYER_STRIDE' --include=*.rs` found
//! no Rust test reading these constants, and the file's own "Do not hand-edit" header was the only
//! enforcement.
//!
//! That matters because the failure is silent. If a constant drifts — a hand edit, or the
//! exporter's layout order changing without regenerating — `gpt2_infer.wk`,
//! `gpt2_forward_bench.wk` and `gpt2_forward_bench_par.wk` index the blob at wrong ELEMENT offsets
//! and compute garbage, while `cargo test` stays green: the examples gate runs them with the blob
//! absent, so both backends take the `-1` early return, and the only real detector
//! (`tools/verify_gpt2.py`) is manual and needs the uncommitted 500 MB blob.
//!
//! `compute_offsets()` is pure integer arithmetic over six dims and needs neither torch nor the
//! blob, so it can simply be re-derived here — from the exporter's own `LAYER_TENSORS` order,
//! parsed out of the script, so that reordering the layout there fails this test instead of
//! silently invalidating the committed constants.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("..").join("..")
}

/// Parse `const GPT2_NAME: i64 = <int>;` out of `examples/gpt2_config.wk`.
fn wk_constants() -> BTreeMap<String, i64> {
    let path = repo_root().join("examples").join("gpt2_config.wk");
    let src = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    let mut out = BTreeMap::new();
    for line in src.lines() {
        let line = line.trim();
        let Some(rest) = line.strip_prefix("const GPT2_") else {
            continue;
        };
        let Some((name, rest)) = rest.split_once(':') else {
            continue;
        };
        let Some((_ty, value)) = rest.split_once('=') else {
            continue;
        };
        // Strip the trailing `;` and any `// comment`.
        let value = value
            .split("//")
            .next()
            .unwrap()
            .trim()
            .trim_end_matches(';');
        if let Ok(v) = value.trim().parse::<i64>() {
            out.insert(name.trim().to_string(), v);
        }
    }
    assert!(
        out.len() > 20,
        "parsed only {} constants out of examples/gpt2_config.wk — the parser or the file shape \
         changed, and this gate would pass vacuously",
        out.len()
    );
    out
}

/// Parse `NAME = <int>` top-level dims and the ordered `LAYER_TENSORS` list out of the exporter.
fn exporter_layout() -> (BTreeMap<String, i64>, Vec<(String, String)>) {
    let path = repo_root().join("tools").join("export_gpt2.py");
    let src = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));

    let mut dims = BTreeMap::new();
    for line in src.lines() {
        let code = line.split('#').next().unwrap().trim();
        let Some((name, value)) = code.split_once('=') else {
            continue;
        };
        let (name, value) = (name.trim(), value.trim());
        if !name.chars().all(|c| c.is_ascii_uppercase() || c == '_') || name.is_empty() {
            continue;
        }
        if let Ok(v) = value.parse::<i64>() {
            dims.insert(name.to_string(), v);
        }
    }

    // `LAYER_TENSORS = [ ("LN1G", D), ("WQ", D * D), ... ]` — take the entries in source order.
    let start = src
        .find("LAYER_TENSORS = [")
        .expect("tools/export_gpt2.py no longer defines LAYER_TENSORS");
    let body = &src[start..];
    let end = body.find(']').expect("unterminated LAYER_TENSORS list");
    let body = &body[..end];
    let mut tensors = Vec::new();
    for chunk in body.split('(').skip(1) {
        let Some(close) = chunk.find(')') else {
            continue;
        };
        let entry = &chunk[..close];
        let Some((name, size)) = entry.split_once(',') else {
            continue;
        };
        tensors.push((
            name.trim().trim_matches('"').to_string(),
            size.trim().to_string(),
        ));
    }
    assert!(
        tensors.len() >= 16,
        "parsed only {} LAYER_TENSORS entries — the parser or the script shape changed",
        tensors.len()
    );
    (dims, tensors)
}

/// Evaluate one `LAYER_TENSORS` size expression: a product of dim names (`D`, `D * D`, `DFF * D`).
fn eval_size(expr: &str, d: i64, dff: i64) -> i64 {
    expr.split('*')
        .map(|f| match f.trim() {
            "D" => d,
            "DFF" => dff,
            other => panic!("unhandled LAYER_TENSORS size factor `{other}` in `{expr}`"),
        })
        .product()
}

/// Every `const GPT2_*` in the committed config must equal what the exporter's `compute_offsets()`
/// recurrence produces from the six dims, in the exporter's own tensor order.
#[test]
fn gpt2_config_matches_the_exporter_layout() {
    let wk = wk_constants();
    let (py, tensors) = exporter_layout();

    let get = |k: &str| -> i64 {
        *wk.get(k)
            .unwrap_or_else(|| panic!("examples/gpt2_config.wk has no `const GPT2_{k}`"))
    };

    // 1. The dims themselves must match the exporter's literals.
    for name in ["D", "H", "VOCAB", "POS", "LAYERS", "SEQ"] {
        let want = *py
            .get(name)
            .unwrap_or_else(|| panic!("tools/export_gpt2.py no longer defines `{name}`"));
        assert_eq!(get(name), want, "GPT2_{name} disagrees with the exporter");
    }
    let (d, h) = (get("D"), get("H"));
    // The exporter derives these: `HD = D // H`, `DFF = 4 * D`.
    assert_eq!(get("HD"), d / h, "GPT2_HD must be D / H");
    assert_eq!(get("DFF"), 4 * d, "GPT2_DFF must be 4 * D");
    let dff = get("DFF");

    // 2. The within-layer running sum, in the exporter's tensor order.
    let mut off = 0i64;
    let mut names = Vec::new();
    for (name, size_expr) in &tensors {
        assert_eq!(
            get(&format!("REL_{name}")),
            off,
            "GPT2_REL_{name} disagrees with the exporter's running offset"
        );
        off += eval_size(size_expr, d, dff);
        names.push(name.clone());
    }
    let layer_stride = off;
    assert_eq!(
        get("LAYER_STRIDE"),
        layer_stride,
        "GPT2_LAYER_STRIDE disagrees with the sum of the layer tensors"
    );

    // Nothing extra and nothing missing: every REL_ constant must correspond to a layer tensor.
    let mut stray: Vec<&String> = wk
        .keys()
        .filter(|k| k.starts_with("REL_"))
        .filter(|k| !names.iter().any(|n| format!("REL_{n}") == **k))
        .collect();
    stray.sort();
    assert!(
        stray.is_empty(),
        "examples/gpt2_config.wk declares REL_ constants the exporter's LAYER_TENSORS does not \
         produce: {stray:?}"
    );

    // 3. The top-level blob layout.
    let off_wte = 0i64;
    let off_wpe = off_wte + get("VOCAB") * d;
    let off_layer0 = off_wpe + get("POS") * d;
    let off_lnfg = off_layer0 + get("LAYERS") * layer_stride;
    let off_lnfb = off_lnfg + d;
    let total = off_lnfb + d;
    assert_eq!(get("OFF_WTE"), off_wte, "GPT2_OFF_WTE");
    assert_eq!(get("OFF_WPE"), off_wpe, "GPT2_OFF_WPE");
    assert_eq!(get("OFF_LAYER0"), off_layer0, "GPT2_OFF_LAYER0");
    assert_eq!(get("OFF_LNFG"), off_lnfg, "GPT2_OFF_LNFG");
    assert_eq!(get("OFF_LNFB"), off_lnfb, "GPT2_OFF_LNFB");
    assert_eq!(get("TOTAL_WEIGHTS"), total, "GPT2_TOTAL_WEIGHTS");

    // 4. An external anchor, so a self-consistent but wrong table is still caught: this is the
    // canonical GPT-2 small parameter count.
    assert_eq!(
        total, 124_439_808,
        "the layout no longer totals GPT-2 small's parameter count"
    );
}
