[package]
name = "mercury_opt"
description = "The Mercury optimizer: a pass manager and MIR transforms."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
mercury_mir = { workspace = true }

[dev-dependencies]
mercury_span = { workspace = true }
mercury_parser = { workspace = true }
mercury_sema = { workspace = true }
mercury_mir_build = { workspace = true }
mercury_interp = { workspace = true }
