[package]
name = "mercury_sema"
description = "Semantic analysis for Mercury: name resolution, type checking, shape checking."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
mercury_span = { workspace = true }
mercury_diag = { workspace = true }
mercury_ast = { workspace = true }
mercury_types = { workspace = true }

[dev-dependencies]
mercury_parser = { workspace = true }
